client-id: kgk
client-secret: f710678b-83a8-4f4f-9946-6fc9ec4a0dfa
discovery-url: https://sso-mrt.apps.ocp4.rhocplab.com/auth/realms/mrt
enable-default-deny: true
secure-cookie: false
skip-openid-provider-tls-verify: true
match-claims:
  aud: kgk
  iss: https://sso-mrt.apps.ocp4.rhocplab.com/auth/realms/mrt
encryption_key: AgXa7xRcoClDEU0ZDSH4X0XhL5Qy2Z2j
listen: :8080
redirection-url: http://web-mrt.apps.ocp4.rhocplab.com
upstream-url: http://frontend-mrt.apps.ocp4.rhocplab.com
resources:
- uri: /*
  methods:
  - GET
  - POST
- uri: /public/*
  white-listed: true
- uri: /favicon
  white-listed: true
- uri: /css/*
  white-listed: true
- uri: /js/*
  white-listed: true
- uri: /img/*
  white-listed: true
